version: '2'
services: 
  loki:
    hostname: loki
    image: grafana/loki:2.8.4
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./volumes/loki/etc:/etc/loki

  grafana:
    image: grafana/grafana:10.0.3
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./volumes/grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
