version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

  promtail:
    image: grafana/promtail:main 
    restart: unless-stopped
    hostname: promtail
    ports:
      - "3100:3100"
    volumes:
      - ./volumes/promtail/promtail.yaml:/etc/promtail/docker-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yaml

  kafka:
    hostname: kafka
    image: confluentinc/cp-kafka:7.4.1
    restart: unless-stopped
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    depends_on:
      - zookeeper
    ports:
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  producer:
    build: ./Producer
    restart: unless-stopped
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    depends_on:
      - kafka

  consumer:
    build: ./Consumer
    restart: unless-stopped
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    depends_on:
      - kafka
      - producer